sudo: false
language: node_js

node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.12"
  - "iojs-1"
  - "iojs-2"
  - "iojs-3"
  - "4"
  - "5"

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" = "0.6" ] && npm conf set strict-ssl false || true'
